name: Continuos Integration

on: [pull_request, push]

jobs:
  contiuos_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update libs
        run: |
          apt-get update
          apt-get upgrade
          apt install libx11-dev
          apt install libxext-dev
          apt install libbsd-dev
          apt install clang
      - name: build and test
        run: |
          make
          ./cub3D
          ./cub3D test1 test2
          ./cub3D dasd
          ./cub3D .cub
