name: Continuos Integration

on: [pull_request, push]

jobs:
  contiuos_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update libs
        run: |
          sudo apt install libx11-dev
          sudo apt install libxext-dev
          sudo apt install libbsd-dev
          sudo apt install clang
      - name: build and test
        run: |
          make
          ./tests.sh
