name: Continuos Integration

on: [pull_request, push]

jobs:
  contiuos_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update libs
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install libx11-dev
          sudo apt install libxext-dev
          sudo apt install libbsd-dev
          sudo apt install clang
      - name: build and test
        run: |
          make
          ./cub3D
          ./cub3D test1 test2
          ./cub3D dasd
          ./cub3D .cub
